# Generated by Django 4.0.6 on 2022-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="main_url",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
