version: "3.9"
   
services:
  show-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python shows_worker.py
    volumes:
      - .:/code
    depends_on:
      - postgres-show
    environment:
      - RABBITMQ_URL=amqps://bwvvcnww:b4WjIHCwAtizbAo72daDwnt3IoOVgRlx@shrimp.rmq.cloudamqp.com/bwvvcnww
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  postgres-show:
    image: postgres
    container_name: postgres-show
    hostname: postgres-show
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api-show:
    build: .
    command: python manage.py runserver 0.0.0.0:8015
    volumes:
      - .:/code
    ports:
      - "8015:8015"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - postgres-show
    depends_on:
      - postgres-show
networks: 
  default: 
    external: 
      name: sub_net
