# Generated by Django 4.0.6 on 2022-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['num_of_favorites']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='air_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='end_date',
            field=models.DateField(),
        ),
    ]
