# Generated by Django 4.0.6 on 2022-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
