# Generated by Django 4.0.6 on 2022-07-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='show',
            new_name='show_id',
        ),
    ]
