# Generated by Django 4.0.6 on 2022-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_show_options_alter_episode_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='num_of_favorites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
