# Generated by Django 4.0.6 on 2022-07-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_rename_show_character_show_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='show_id',
            new_name='show',
        ),
    ]
