# Generated by Django 4.0.6 on 2022-07-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_show_num_of_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
