# Generated by Django 4.0.6 on 2022-07-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_show_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='show_id',
            new_name='show',
        ),
    ]
