# Generated by Django 4.0.6 on 2022-07-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_rename_show_id_favorites_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='number_of_episode',
            new_name='epi_num',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='name',
            new_name='season_num',
        ),
    ]
