# Generated by Django 4.0.6 on 2022-07-25 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_rename_number_of_episode_episode_epi_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_num',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
