# Generated by Django 4.0.6 on 2022-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.BooleanField(choices=[(0, 'Normal User'), (1, 'Admin')], default=0),
        ),
    ]
